### ISSUE TITLE
FIPS CCLF Bug

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/medicare_cclf_connector#49]
https://thetuvaproject.slack.com/archives/C03DET9ETK3/p1686948353945099

**Comment by aneiderhiser** [comment]
Also would be good to update the name of the folder with the final models to "final".  Currently this folder is called "core" which is confusing, since it's different than the core data model.

**Comment by dignifi-richard** [comment]
I have a branch to address these issues but will need permission to commit the branch and open a PR.
 
Includes:
- [x] Updates Eligibility model to use ANSI FIPS state codes instead of SSA for beneficiary state codes in CCLF8 - Beneficiary Demographics
- [x] Change 'Core' folder / model naming to to 'Final'

**Comment by dignifi-richard** [comment]
Opened this PR to address and close: https://github.com/tuva-health/medicare_cclf_connector/pull/50
